account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import include, re_path
from . import views
from django.urls import path



urlpatterns = [
    path('ajax/load_district/', views.load_district, name='load_district'),
    path('change_password/', views.change_password, name="change_password"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('index/', views.indexPage, name="index"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('info/', views.info, name="info"),
    path('', views.info2, name="info2"),
    path('add_College/', views.add_College, name="add_College"),
    path('Project/',views.Project, name="Project"),
    path('Guide/',views.Guide, name="Guide"),
    path('view_Guide/',views.view_Guide, name="view_Guide"),

    path('launch/',views.launch, name="launch"),
    path('curtain/',views.curtain, name="curtain"),

#path for guide view
    path('Guide_View/<str:pk>/',views.Guide_View, name="Guide_View"),
    path('view_Project/<str:pk>/',views.view_Project, name="view_Project"),
    path('total_survey/',views.total_survey, name="total_survey"),
    path('profile_update/',views.profile_update, name="profile_update"),
    path('view_survey/',views.view_survey, name="view_survey"),
    path('final_submit/<str:pk>/',views.final_submit, name="final_submit"),
    path('delete/<str:pk>/',views.delete, name="delete"),
    path('Reviewer/',views.Reviewer, name="Reviewer"),
    path('add_reviewer/',views.add_reviewer, name="add_reviewer"),
    path('reviewer_list/',views.reviewer_list, name="reviewer_list"),
    path('ajax/load_district/', views.load_district, name='load_district'),
    path('ajax/load_guide/', views.load_guide, name='load_guide'),
    path('Remarks/',views.Remarks, name="Remarks"),
    path('ViewRemarks/<str:pk>/',views.ViewRemarks, name="ViewRemarks"),
    path('updateRemarks/<str:pk>/',views.updateRemarks, name="updateRemarks"),
    path('AssignReviewer/<str:pk>/',views.AssignReviewer, name="AssignReviewer"),
    path('ReviewerRemarks/',views.ReviewerRemarks, name="ReviewerRemarks"),
    path('StudentGuide/',views.StudentGuide, name="StudentGuide"),
    path('StudentProject/',views.StudentProject, name="StudentProject"),
    # re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     views.activate, name='activate'),
    # path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
         name="password_reset_complete"),
    path('college/', views.CollegeListView.as_view(),
         name='college-list'),
    path('college/<int:pk>', views.CollegeDetailView.as_view(),
         name='college-detail'),
    path('college/create', views.CollegeCreateView.as_view(),
         name='college-create'),
    path('college/<int:pk>/update', views.CollegeUpdateView.as_view(),
         name='college-update'),
    path('college/<int:pk>/delete', views.CollegeDeleteView.as_view(),
         name='college-delete'),


]

handler404 = 'account.views.handler404'
handler500 = 'account.views.handler500'

ccras/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('/captcha/',include("captcha.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models
from uuid import uuid4
from django.contrib.sessions.models import Session
from django.conf import settings

# from multiselectfield import MultiSelectField

# create your model here.

# for state and district models here
class State_Study(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

class State(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name


class District(models.Model):
    state = models.ForeignKey(State, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name


class Subject_Area(models.Model):
    Subject_Area = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.Subject_Area


class Name_Of_Department(models.Model):
    Course = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.Course


# For registration modelis here
class College(models.Model):
    # College_ID = models.PrimaryKey(User, null=True, blank=True, on_delete=models.CASCADE)

    # College_Name_Option = [('AIIMS', 'AIIMS'), ('JNU', 'JNU'), ('SBT', 'SBT'),('DU', 'DU'), ('IIT Delhi', 'IIT Delhi'), ('NIT Delhi', 'NIT Delhi') ]
    College_Name = models.CharField(max_length=500, blank=True, null=True)
    College_Address = models.CharField(max_length=100, blank=True, null=True)
    State = models.CharField(max_length=100, blank=True, null=True)
    City = models.CharField(max_length=100, blank=True, null=True)
    Pincode = models.CharField(max_length=100, blank=True, null=True)
    Phone_Number = models.CharField(max_length=100, blank=True, null=True)
    Updated_On = models.DateField(auto_now=False, null=True, blank=True, auto_now_add=False, )
    Remarks = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        # return  str(self.State) + str(' --- ') + str(self.College_Name)
        return str(self.College_Name)

    class Meta:
        ordering = ('State',)


class Registration(models.Model):
    Title_option = [('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')]
    # Username = models.CharField(max_length=100, blank=True, null=True)
    Email_ID = models.CharField(max_length=100, blank=True, null=True)
    # Password = models.CharField(max_length=100, blank=True, null=True)
    # Re_Enter_Password = models.CharField(max_length=100, blank=True, null=True)
    First_name = models.CharField(max_length=100, null=True, validators=[MaxLengthValidator(100)])
    Last_name = models.CharField(max_length=100, null=True, validators=[MaxLengthValidator(100)])

    User_ID = models.OneToOneField(User, null=True, related_name='register_user', blank=True, on_delete=models.CASCADE)
    Date_Of_Birth = models.DateField(auto_now=False, null=True, auto_now_add=False, )
    Full_Name = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])

    State = models.ForeignKey(State, null=True, on_delete=models.CASCADE,verbose_name="Student Residence State")
    District = models.ForeignKey(District, null=True, on_delete=models.CASCADE)

    City = models.CharField(max_length=100, null=True)
    Address_Line1 = models.CharField(max_length=500, null=True, validators=[MaxLengthValidator(500)])
    Address_Line2 = models.CharField(max_length=500, blank=True, null=True, validators=[MaxLengthValidator(500)])
    Pincode = models.CharField(max_length=100, blank=True, null=True)
    Name_Of_Department = models.CharField(max_length=200, blank=True, null=True, validators=[MaxLengthValidator(500)])
    # College_Name = models.CharField(max_length=100, blank=True, null=True)
    # College_Name_Option = [('AIIMS', 'AIIMS'), ('JNU', 'JNU'), ('SBT', 'SBT'),('DU', 'DU'), ('IIT Delhi', 'IIT Delhi'), ('NIT Delhi', 'NIT Delhi') ]
    College_Name = models.ForeignKey(College, null=True, blank=True, related_name='collegename',on_delete=models.CASCADE)
    Designation = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(200)])

    Gender_Option = [('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')]
    Gender = models.CharField(max_length=100, null=True, choices=Gender_Option)

    Nationality_Option = [('Indian', 'Indian'), ]
    Nationality = models.CharField(max_length=100, null=True, choices=Nationality_Option, default='Indian')
    Designation = models.CharField(max_length=100, blank=True, null=True, validators=[MaxLengthValidator(100)])
    Course_Details = models.CharField(max_length=200, blank=True, null=True, validators=[MaxLengthValidator(200)])
    Date_Of_Joining_Course = models.DateField(auto_now=False, blank=True, null=True, auto_now_add=False, )

    # Course_Option = [('BAMS', 'BAMS'), ('BioTechnology', 'BioTechnology'), ('BioInformatic', 'BioInformatic')]
    Course_Option = [('BAMS', 'BAMS')]
    Course = models.CharField(max_length=100, blank=True, null=True, choices=Course_Option)

    Years_Option = [('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')]
    Years = models.CharField(max_length=100, blank=True, null=True, choices=Years_Option)

    Role_Option = [('Student', 'Student'), ('Guide', 'Guide'), ]
    Role = models.CharField(max_length=100, null=True, blank=True, choices=Role_Option)

    Correspondence_Sent_To_Option = [('Home', 'Home'), ('College', 'College'), ]
    Correspondence_Sent_To = models.CharField(max_length=100, blank=True, null=True, choices=Correspondence_Sent_To_Option)

    Last_Qualifying_Exam_Marksheet = models.FileField(null=True, blank=True, upload_to='uploads/%Y/%m/%d/')
    Ncism_Teachers_Code = models.CharField(max_length=100, blank=True, null=True)
    is_reviewer = models.BooleanField(default=False)
    Alterner_Email_id = models.CharField(max_length=100, blank=True, null=True)
    mobile = models.CharField(max_length=100, blank=True, null=True)
    Telephone_No = models.CharField(max_length=100, blank=True, null=True)
    OTP_Verified = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)
    Date_Of_Joining = models.DateField(auto_now=False, blank=True, null=True, auto_now_add=False, )
    Type_Of_Faculty = models.CharField(max_length=100, blank=True, null=True)
    Updated_On = models.DateField(auto_now=False, blank=True, null=True, auto_now_add=False, )
    Student_study_state = models.ForeignKey(State_Study, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.First_name) + " " + str(self.Last_name) + "----" + str(self.College_Name)
        # return str(self.pk)


class Guide_Info(models.Model):
    User_ID = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    # College_ID = models.PrimaryKey(User, null=True, blank=True, on_delete=models.CASCADE)
    Full_Name = models.CharField(max_length=100, blank=True, null=True)
    Designation = models.CharField(max_length=100, blank=True, null=True)
    Name_Of_Department = models.CharField(max_length=100, blank=True, null=True)
    Address_Line1 = models.CharField(max_length=100, blank=True, null=True)
    Address_Line2 = models.CharField(max_length=100, blank=True, null=True)
    College_Name = models.ForeignKey(College, null=True, blank=True, on_delete=models.CASCADE)

    # College_Name_Option = [('AIIMS', 'AIIMS'), ('JNU', 'JNU'), ('SBT', 'SBT'),('DU', 'DU'), ('IIT Delhi', 'IIT Delhi'), ('NIT Delhi', 'NIT Delhi') ]
    # College_Name = models.CharField(max_length=100, blank=True, null=True,choices=College_Name_Option)
    State = models.ForeignKey(State, null=True, blank=True, on_delete=models.CASCADE)
    District = models.ForeignKey(District, null=True, blank=True, on_delete=models.CASCADE)

    City = models.CharField(max_length=100, blank=True, null=True)
    Pincode = models.CharField(max_length=100, blank=True, null=True)
    Mobile_Number = models.CharField(max_length=100, blank=True, null=True)
    Telephone_No = models.CharField(max_length=100, blank=True, null=True)
    # Nationality = models.CharField(max_length=100, blank=True, null=True)
    Nationality_Option = [('Indian', 'Indian'), ('Foreign', 'Foreign'), ]
    Nationality = models.CharField(max_length=100, blank=True, null=True, choices=Nationality_Option)
    # Gender = models.CharField(max_length=100, blank=True, null=True)
    Gender_Option = [('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')]
    Gender = models.CharField(max_length=100, blank=True, null=True, choices=Gender_Option)
    Email_id = models.CharField(max_length=100, blank=True, null=True)
    Updated_On = models.DateField(auto_now=False, null=True, blank=True, auto_now_add=False, )
    Remarks = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.Full_Name) + str(self.pk)


class Project_info(models.Model):
    # Spark_ID = models.PrimaryKey(User, null=True, blank=True, on_delete=models.CASCADE)
    User_ID = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    Guide_ID = models.OneToOneField(Registration, related_name="GUIDE_ID", null=True, on_delete=models.CASCADE, limit_choices_to={'Role': 'Guide',})
    Reviewer_ID1 = models.ForeignKey(Registration, related_name="Reviewer1_ID", null=True, blank=True, on_delete=models.CASCADE, limit_choices_to={'is_reviewer': True})
    Reviewer_ID2 = models.ForeignKey(Registration, related_name="Reviewer2_ID", null=True, blank=True, on_delete=models.CASCADE, limit_choices_to={'is_reviewer': True})
    Reviewer_ID3 = models.ForeignKey(Registration, related_name="Reviewer3_ID", null=True, blank=True, on_delete=models.CASCADE, limit_choices_to={'is_reviewer': True})

account/templates/ReviewerRemarks.html
{%  extends 'main.html' %}
{% block content %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--<script src="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css"></script>-->
<!--<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>-->
<!--<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>-->
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );



</script>
<br>

<div class="container">
	<div class="card">
		<table class="table table-striped table-bordered" id="example" style="width:100%">
			<thead>
			<tr>
				<th>Spark ID</th>

<!--				<th>Student Name</th>-->

<!--				<th>Guide Name</th>-->
				<th>College Name</th>
				<th>Project Title</th>

				<!--      <th>Marks</th>-->
				<!--      <th>Reviewer_ID</th>-->
				<th>Updated Date</th>


				<th>View</th>
				<th>Update</th>


			</tr>
			</thead>
			<tbody>

			{% for customer in form6 %}
			<tr>
				<td>{{customer.unique_id}}</td>
<!--				<td>{{customer.Registration_ID.First_name}}</td>-->
<!--				<td>{{customer.Guide_ID}}</td>-->
				<td>{{customer.Registration_ID.College_Name}}</td>
				<td>{{customer.Project_Title}}</td>
				<!--      <td>{{customer.Total_Marks}}</td>-->
				<!--      <td>{{customer.Reviewer_ID.First_name }}</td>-->
				<td>{{customer.Date_Created }}</td>


				<td><a class="btn btn btn-success" href="{% url 'ViewRemarks' customer.id  %}">View</a></td>
				<td>
					<a class="btn btn btn-info" href="{% url 'updateRemarks' customer.id  %}">Update</a>
				</td>


				<!--    <td>-->
				<!--	      {% if Total_Marks_review %}-->
				<!--	    <a class="btn btn btn-info" href="{% url 'updateRemarks' customer.id  %}">Update</a>-->
				<!--	     {% endif %}-->
				<!--    </td>-->


			</tr>
			{% endfor %}
			</tbody>
			<tfoot>
			<th>Spark ID</th>

<!--			<th>Student Name</th>-->

<!--			<th>Guide Name</th>-->

			<th>College Name</th>
			<th>Project Title</th>

			<!--      <th>Marks</th>-->
			<!--      <th>Reviewer_ID</th>-->

			<th>Updated Date</th>


			<th>View</th>
			<th>Update</th>


			</tfoot>
		</table>
	</div>a
</div>

<!--{% for i in form5 %}-->
<!--{{i}}////////{{i.project.Registration_ID}}-->
<!--{% endfor %}-->
<!--<hr>-->
<!--{% for i in form6 %}-->
<!--{{i}}-->
<!--{{i.project_ID}}{{i.project_ID}}-->
<!--{% for ii in i.project_ID.all %}-->
<!--{{ii.Total_Marks_review}}-->
<!--{{ii.Remarks}}-->
<!--{% endfor %}-->

<!--<hr>-->
<!--{% endfor %}-->

<!--{% for i in form7 %}-->
<!--{{i}}-->
<!--{% endfor %}-->


{% endblock %}

account/templates/add_reviewer.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}
{% load extra %}
{% load add_attr %}



{% if form1.errors %}
{% for field in form1 %}
{% for error in field.errors %}
<div class="alert alert-danger">
	{{field.label}} ---- {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% endif %}
{% if form2.errors %}
{% for field in form2 %}
{% for error in field.errors %}
<div class="alert alert-danger">
	{{field.label}} ---- {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% endif %}
<body class="hold-transition register-page">
<div class="register-box">
	<div class="register-logo">
		<a href="../../index2.html"><b>Add Reviewer</b></a>
	</div>
	<div class="register-box-body">
		<form method="POST" data-district-url="{% url 'load_district' %}" id="personForm" enctype="multipart/form-data" action="">
			{% csrf_token %}
			{{ form.management_form }}
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form1.username.label}}</label>
						{{form1.username|addclass:'form-control required1'}}
						{{form1.username.errors}}
						<span class="glyphicon glyphicon-user form-control-feedback"></span>
						Required. 150 characters or fewer. Letters, digits only.
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form1.email.label}}</label>
						{{form1.email|addclass:'form-control required1'}}
						{{form1.email.errors}}
						<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form1.password1.label}}</label>
						{{form1.password1|addclass:'form-control required1'}}
						{{form1.password1.errors}}
						<span class="glyphicon glyphicon-lock form-control-feedback"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form1.password2.label}}</label>
						{{form1.password2|addclass:'form-control required1'}}
						{{form1.password2.errors}}
						<span class="glyphicon glyphicon-log-in form-control-feedback"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<ul>
					<li>Your password can't be too similar to your other personal information.</li>
					<li>Your password must contain at least 8 characters.</li>
					<li>Your password can't be a commonly used password.</li>
					<li>Your password can't be entirely numeric.</li>
				</ul>


			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.First_name.label}}</label>
						{{form2.First_name|addclass:'form-control required1'}}
						{{form2.First_name.errors}}
						<span class="glyphicon glyphicon-text-color form-control-feedback"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Last_name.label}}</label>
						{{form2.Last_name|addclass:'form-control required1'}}
						{{form2.Last_name.errors}}
						<span class="glyphicon glyphicon-text-color form-control-feedback"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Date_Of_Birth.label}}</label>
						{{form2.Date_Of_Birth|addclass:'form-control required1'}}
						{{form2.Date_Of_Birth.errors}}
						<!--                        <span class="glyphicon glyphicon-list form-control-feedback"></span>-->
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Gender.label}}</label>
						{{form2.Gender|addclass:'form-control required1'}}
						{{form2.Gender.errors}}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.State.label}}</label>
						{{form2.State|addclass:'form-control required1'}}
						{{form2.State.errors}}
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.District.label}}</label>
						{{form2.District|addclass:'form-control required1'}}
						{{form2.District.errors}}
						<!--                        <span class="glyphicon glyphicon-list form-control-feedback"></span>-->
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Address_Line1.label}}</label>
						{{form2.Address_Line1|addclass:'form-control required1'}}
						{{form2.Address_Line1.errors}}
						<!--                        <span class="glyphicon glyphicon-list form-control-feedback"></span>-->
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Address_Line2.label}}</label>
						{{form2.Address_Line2|addclass:'form-control'}}
						{{form2.Address_Line2.errors}}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.City.label}}</label>
						{{form2.City|addclass:'form-control required1'}}
						{{form2.City.errors}}
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Pincode.label}}</label>
						{{form2.Pincode|addclass:'form-control'}}
						{{form2.Pincode.errors}}
						<!--                        <span class="glyphicon glyphicon-list form-control-feedback"></span>-->
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">{{form2.Nationality.label}}</label>
						{{form2.Nationality|addclass:'form-control required1'}}
						{{form2.Nationality.errors}}
						<!--                        <span class="glyphicon glyphicon-list form-control-feedback"></span>-->
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group has-feedback">
						<label class="col-md font-weight-bolder text-dark text-left">Enrolling as a Reviewer</label>
						{{form2.is_reviewer|addclass:'required1'}}
						{{form2.is_reviewer.errors}}
					</div>
				</div>
			</div>
			<br>
			<div class="row">
						<!-- /.col -->
						<div class="col-xs-4">
							<button type="submit" id="submit1" class="btn btn-primary btn-block btn-flat">Register</button>
						</div>
						<!-- /.col -->
					</div>

		</form>
		{{form.errors}}

		<!-- /.form-box -->
	</div>
</div>
<!--<script>-->
<!--		//Query All input fields-->
<!--		var form_fields = document.getElementsByTagName('input')-->
<!--		form_fields[1].placeholder='Username...';-->
<!--		form_fields[2].placeholder='Email...';-->
<!--		form_fields[3].placeholder='Enter password...';-->
<!--		form_fields[4].placeholder='Re-enter Password...';-->
<!--		form_fields[4].placeholder='Re-enter Password...';-->
<!--		form_fields[5].placeholder='First Name...';-->
<!--		form_fields[6].placeholder='Last Name...';-->
<!--		for (var field in form_fields){-->
<!--			form_fields[field].className += ' form-control'-->
<!--		}-->


<!--</script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
	$(document).ready(function() {
		$('#submit1').click(function(e) {
			var isValid = true;
			$('.required1').each(function() {
				if ($.trim($(this).val()) == '') {
					isValid = false;
					$(this).css({
						"border": "1px solid red",
						"background": "#FFCECE"
					});
					alert($(this).attr("name") + " " + 'field is empty')
				}
				else {
					$(this).css({
						"border": "",
						"background": ""
					});
				}
			});
			if(!$("#id_is_reviewer").is(':checked')){
	confirm("Please tick is Enrolling as a Reviewer")
	isValid = false;
	$(id_is_reviewer).css({
	"border": "1px solid red",
	"background": "#FFCECE"
	});
	}
			if (isValid == false)
			e.preventDefault();
			else
			alert('Thank you for submitting');
		});
	});


</script>
<script>
			$(document).ready(function(){
				$('#id_Role').on('change', function(){
					var demovalue = $(this).val();
					if(demovalue == 'Student'){
						$(".student").show();
						$(".guide1").hide();
					}
					else if(demovalue == 'Guide')
					{
					$(".student").hide();
					$(".guide1").show();
					}
					else
					{
					$(".student").hide();
					$(".guide1").hide();
					}
				});
				$(".student").hide();
				$(".guide1").hide();
			});


</script>
<script>
	$(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
	})

</script>

<script>
	$(document).ready(function(){
	$("#id_State").change(function () {
	const url = $("#personForm").attr("data-district-url");
	const DistrictId = $(this).val();  // get the selected country ID from the HTML input
	$.ajax({                       // initialize an AJAX request
	url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
	data: {
	'district_id': DistrictId       // add the town id to the GET parameters
	},
	success: function (data) {   // `data` is the return of the `load_cities` view
	console.log(data)
	$("#id_District").html(data);
	}
	});
	});
	});





</script>












{% endblock %}

account/templates/load_guide.html
<option value="">---------</option>
{% for city in continent %}
<option value="{{ city.id }}">{{ city.First_name }}   {{ city.Last_name }} --- {{city.College_Name__College_Name}}  </option>
{% endfor %}